FROM apache/airflow:2.9.3

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends docker.io \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-docker==3.10.0 \
    pandas==2.2.2 \
    pyarrow==16.1.0 \
    psycopg2-binary==2.9.9
